export const rules = [
    {"type": "suitOrValue", "isSuit": true, "validKeys": ["diamonds"], "penalty": "Cultural appropriation", "suitOrValueNeeded": true, "actionNeeded": {"ace": "uno", "two": "dos", "three": "tres", "four": "cuatro", "five": "cinco", "six": "seis", "seven": "siete", "eight": "ocho", "nine": "nueve", "ten": "diez", "jack": "once", "queen": "doce", "king": "trece"}},
    {"type": "suitOrValue", "isSuit": false, "validKeys": ["queen"], "penalty": "Didn't care about the monkey", "suitOrValueNeeded": false, "actionNeeded": "where's the monkey?"},
    {"type": "suitOrValue", "isSuit": false, "validKeys": ["ace"], "penalty": "Didn't find the monkey", "suitOrValueNeeded": false, "actionNeeded": "there's the monkey!"},
    {"type": "suitOrValue", "isSuit": false, "validKeys": ["two", "three", "five", "seven", "jack", "king"], "penalty": "Failure to be good at maths", "suitOrValueNeeded": false, "actionNeeded": "prime"}, 
    {"type": "suitOrValue", "isSuit": false, "validKeys": ["ace", "five", "ten"], "penalty": "Failure to dispense wise sayings", "suitOrValueNeeded": false, "actionNeeded": "rome wasn't built in a day"},
    {"type": "suitOrValue", "isSuit": false, "validKeys": ["jack"], "penalty": "Failure to be polite", "suitOrValueNeeded": false, "actionNeeded": "knock knock"},
    {"type": "value sequence", "numberOfValuesToCheck": 2, "validValues": [["jack", "ace"], ["jack", "two"], ["jack", "three"], ["jack", "four"], ["jack", "five"], ["jack", "six"], ["jack", "seven"], ["jack", "eight"], ["jack", "nine"], ["jack", "ten"], ["jack", "queen"], ["jack", "king"]], "penalty": "Failure to open the door to such a gentleman", "actionNeeded": "who's there?"},
    {"type": "value sequence", "numberOfValuesToCheck": 3, "validValues": [["ace", "ace", "nine"]], "penalty": "Failure to save lives", "actionNeeded": "emergency emergency!"},
    {"type": "value sequence", "numberOfValuesToCheck": 2, "validValues": [["ace", "seven"], ["seven", "ace"], ["two", "six"], ["six", "two"], ["three", "five"], ["four", "four"]], "penalty": "Failure to do basic arithmetic", "actionNeeded": "maths"},
    {"type": "value sequence", "numberOfValuesToCheck": 2, "validValues": [["two", "four", "six", "eight"]], "penalty": "Failure to complete the cheer", "actionNeeded": "who do we appreciate?"},
    {"type": "suit sequence", "numberOfValuesToCheck": 5, "validValues": [["hearts", "hearts", "hearts", "hearts", "hearts"]], "penalty": "Failure to introduce the queen in Alice of Wonderland", "actionNeeded": "welcome, queen of hearts"},
    {"type": "suit sequence", "numberOfValuesToCheck": 3, "validValues": [["spades", "spades", "spades"], ["spades", "spades", "clubs"], ["spades", "clubs", "spades"], ["spades", "clubs", "clubs"], ["clubs", "spades", "spades"], ["clubs", "spades", "clubs"], ["clubs", "clubs", "spades"], ["clubs", "clubs", "clubs"]], "penalty": "Failure to embrace the night", "actionNeeded": "welcome, queen of the darkness"}
]